### ISSUE TITLE
Editor integrations

### ISSUE THREAD

**Issue by byorgey** [byorgey/swarm#100]
The REPL is kind of annoying to use, and other than some cosmetic things like #85 and #75 , fundamentally typing a bunch of code at a REPL is just going to suck.  So I envision that players may want to use an editor that they are comfortable with to write their code, then load it into the REPL.  The only downside to that is they don't get the kind of instant feedback the REPL gives them.  So it would be nice to build out features to make it more pleasant editing Swarm code in various editors.

This is a placeholder that will probably expand into multiple issues.  I don't have much experience building editor support for languages so I'm open to suggestions.  Do we just work on implementing the language server protocol? Are there other things we should do?

**Comment by Anrock** [comment]
I guess first step is to make swam executable work like a compiler\checker of some sort. Something like `swarm --check myscript` and swarm should output errors in some fixed format. This will allow basic integration to most of the editors already.

Bonus points if swarm works like watcher - like [ghcid](https://github.com/ndmitchell/ghcid)

**Comment by TristanCacqueray** [comment]
It might be a fun project to implement the language server protocol, and looking at https://github.com/bkomuves/toy-language-server, it does not sounds too difficult. Though for some reason this does not cover syntax highlighting so we would need to also provide something like https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide for each supported editor.

@byorgey does the language have a name already? Should it be `swarm-lang` ?

**Comment by byorgey** [comment]
> @byorgey does the language have a name already? Should it be `swarm-lang` ?

Sure, unless someone comes up with something really clever, that seems like a good default.

**Comment by byorgey** [comment]
> Do you
> think we should modify the Expr data type so that the typechecker can also fail with source location

We should probably do that eventually.  But the typechecker is not going to be able to make use of it without a major rewrite.  Right now when the typechecker fails with an error, it typically gets spit out of the guts of the `unification-fd` library, and there's absolutely no way to know what location in the source it corresponds to.  In fact, the source location corresponding to the error is not even well-defined at all, since it may have failed because of a combination of constraints generated from various places. 

For improving type error messages (which, to be clear, are currently atrocious), #99 is a first step.  Beyond that I have a concrete idea of something else I'd like to try; I will create another issue for it.

**Comment by byorgey** [comment]
We do have some basic editor integrations now.  They can always be improved, of course, but since this issue is kind of a vague placeholder, I am going to close it.  If there are specific ways that we want to improve the existing editor integrations, or specific new ones we want to add, we can open new issues for those.
