### ISSUE TITLE
Decide on code formatting standards / automatic code formatter

### ISSUE THREAD

**Issue by byorgey** [byorgey/swarm#103]
I have always used `stylish-haskell` in the past, but I'm coming to realize some of its shortcomings.  In particular, the way it vertically lines things up like equals signs and `{-# LANGUAGE #-}` pragmas looks really nice, but it means that making a change to one line can cause many lines to change spuriously, as it shifts things around to get them to line up vertically.  That's really not great for a big project with many collaborators, where there is a higher value on having diffs be as small as possible.

I wonder about using https://github.com/tweag/ormolu .  I hear lots of good things about it, and it claims minimal diffs as one of its design goals. There might be other possibilities too, I'm open to suggestions.

Whatever we decide, I'd ideally like to set up the `restyled.io` bot which automatically creates patches to fix up the formatting.

**Comment by byorgey** [comment]
I tried out `ormolu` to see how it would reformat a couple of the modules.  I don't love it, but I could live with it.

**Comment by TristanCacqueray** [comment]
I don't love it either, in particular because it:

- doesn't preserve import group.
- uses trailing coma in list.
- insists on removing newline in data type definition.

But I could also live with it, as a matter of fact I have `(add-hook 'haskell-mode-hook 'ormolu-format-on-save-mode)` by default in emacs :)

**Comment by byorgey** [comment]
Yeah, I don't like those things either.  Hmm, there's also https://github.com/lspitzner/brittany , does anyone have experience using it?

**Comment by TristanCacqueray** [comment]
Or https://github.com/haskell/stylish-haskell seems more aligned with the current style, and it is provided by HLS.

**Comment by byorgey** [comment]
Yeah, I'm coming to the conclusion that maybe we should just stick with `stylish-haskell` after all.  In the end, for a project like this, I think optimizing for readability by humans is more important than optimizing for minimal diffs.

**Comment by byorgey** [comment]
I tried out `brittany` and I think I generally like the output (it even vertically lines up function arguments, and does much more than `stylish-haskell` to ensure that lines are not too long).  `brittany` is also supported by `restyled.io` and there is a HLS plugin for it: https://hackage.haskell.org/package/hls-brittany-plugin, https://haskell-language-server.readthedocs.io/en/latest/configuration.html#language-specific-server-options .

I pushed the reformatted code to a branch just to show what it would look like: https://github.com/byorgey/swarm/commit/1ffe51179ab8a52f6b0b10b5ed8d3edb6ae1d6d7

**Comment by polux** [comment]
I don't have strong opinions on formatters but note that one main advantage of ormolu over the others is that it uses GHC's parser and supports all language features. For that reason I ended up defaulting to it even though I liked Brittany's output better. There is also fourmolu, a fork or ormolu that is somewhat customizable.

**Comment by polux** [comment]
Actually Brittany uses GHC's parser as well. Maybe it has improved since then but last time I used it it couldn't format many parts of the language yet, like code of the methods of a typeclass.

**Comment by byorgey** [comment]
> like code of the methods of a typeclass.

The README still says it can't do that, but it seems that it actually can: https://github.com/byorgey/swarm/commit/1ffe51179ab8a52f6b0b10b5ed8d3edb6ae1d6d7#diff-615009e8bf5a8001c06d1c5057ed8f1b645c56eecde0c3d38bb1673b22e6d3e3R100 (actually in that specific case I wish it didn't =P)

**Comment by TristanCacqueray** [comment]
brittany looks good to me, I actually used it with the emacs `format-all` package for the LSP module.

**Comment by xsebek** [comment]
I use formolu as it is more configurable then ormolu and imho produces slightly nicer diffs 🙂

**Comment by TristanCacqueray** [comment]
formolu also looks good to me. Moreover I think smaller diff is good to have for dealing with rebase conflict.

**Comment by byorgey** [comment]
Later today I'll also try running `fourmolu` over the codebase and upload another branch so we can compare.

**Comment by byorgey** [comment]
Hmm, but note that `restyled.io` [does not support `fourmolu`](https://docs.restyled.io/available-restylers/).

**Comment by byorgey** [comment]
For comparison, [here is the codebase restyled with fourmolu](https://github.com/byorgey/swarm/commit/f6f478482b1bbfc378cc4c906dd74eff5aae0cbb). I tried to pick some settings that were as close as possible to the current style. Generally speaking, I like it a lot, in fact I think I even like it better than `brittany`.  And it would give us smaller diffs in general.  However, the fact that `restyled.io` doesn't support it is bothersome.  If we're going to adopt a formatting convention then it needs to be built into our CI or else it's going to be a bunch of manual work.  But maybe [we can open a PR to add fourmolu to restyled.io](https://github.com/restyled-io/restyled.io/wiki/Adding-a-Restyler).

**Comment by TristanCacqueray** [comment]
That is looking great! I'll have a look to add support in `restyled.io`

**Comment by TristanCacqueray** [comment]
fourmoulu support is now proposed at https://github.com/restyled-io/restylers/pull/255

**Comment by byorgey** [comment]
Great! I guess the remaining steps are (1) merge the branch with fourmolu formatting applied, (2) set up `restyled.io`.

**Comment by byorgey** [comment]
`restyled.io` is now installed on this repository and should automatically do formatting with fourmolu (opening automatic PRs with formatting fixes if necessary).  Holler if it seems like it's doing anything weird.  Note that the automatic PRs it uses work a lot more smoothly when it's working on branches within the same repo.  This is one reason why, for those with access, I think we should prefer creating PRs from feature branches within this repo itself, rather than a branch in your own fork.
