### ISSUE TITLE
Implement the language server protocol

### ISSUE THREAD

**Issue by byorgey** [byorgey/swarm#110]
As discussed in #100 , we should try implementing the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/).  For inspiration, see https://github.com/bkomuves/toy-language-server and https://github.com/haskell/haskell-language-server .

**Comment by TristanCacqueray** [comment]
I actually started an emacs `swarm-mode` and got an initial lsp service using https://github.com/haskell/lsp/blob/master/lsp/example/Simple.hs to check the file on save. I'll open a PR shortly :)
