### ISSUE TITLE
Command for a robot to find out its own name

### ISSUE THREAD

**Issue by byorgey** [byorgey/swarm#113]
Right now there's no way for a robot to know what its own name is; I propose adding `myname : cmd string` for this purpose. This seems like it might be useful.  For example, if robot A builds robot B which is supposed to fetch something and bring it back to A, robot B needs to be provided with the name of robot A so it can `give` to it.

**Comment by twitu** [comment]
I agree this will be quite useful. Do you think this should hide behind a capability or should be part of the base set of commands?

It would be quite funny to require the robot to bolt on a mirror to "reflect" it's name.

**Comment by byorgey** [comment]
> Do you think this should hide behind a capability or should be part of the base set of commands?
> 
> It would be quite funny to require the robot to bolt on a mirror to "reflect" it's name.

Hah, indeed, why not?  Maybe name is painted on the outside and it needs a mirror to see it.  From a gameplay point of view I don't see any reason that you would need this capability from the beginning; you can probably get by without it for quite a while.
