### ISSUE TITLE
Get thing info

### ISSUE THREAD

**Issue by RustemB** [byorgey/swarm#117]
**Is your feature request related to a problem? Please describe.**
Maybe some function to get info about thing under robot?

**Describe the solution you'd like**
add possible to compare strings then users can implement something like this
```swarm
def isit : string -> bool = \tgt.
    thing <- grab;
    place thing;
    tgt == thing
end;
```

**Describe alternatives you've considered**
or just add any detector capability to check by some detector:
* robot grabs thing
* gives to base
* base add this thing to database
* only then robots can detect this thing inplace

**Comment by byorgey** [comment]
Yes, this will be provided by #96 (there is currently a pull request implementing that in #106 ).  Let us know if that doesn't address what you have in mind!

**Comment by byorgey** [comment]
Actually maybe you are asking about the `ishere` command.  That command will probably be replaced by something else in the future but for now it works like your `isit` command.
