### ISSUE TITLE
List type

### ISSUE THREAD

**Issue by RustemB** [byorgey/swarm#120]
### To get inventory
```ml
> getinventory
["tree", "tree", "flower", "lambda"] : cmd [string]
```
### Or
```ml
[(2, "tree"), (1, "flower"), (1, "lambda")] : cmd [int * string]
```
### but I prefer the first option

**Comment by byorgey** [comment]
Definitely agree this would be a useful feature!  I'll close this since we already have an issue to track it at #97 .

**Comment by RustemB** [comment]
Sorry, haven't seen this issue
