### ISSUE TITLE
Document language server setup

### ISSUE THREAD

**Issue by TristanCacqueray** [byorgey/swarm#123]
Now that we have a LSP implementation with #108 , we need to document how to configure it for the various editors that support language servers (e.g. VSCode, Vim, and Emacs).

This also requires creating the missing editor plugin to handle swarm-lang (e.g. associate to file extension and provide syntax highlighting).

Here is an example of such documentation: https://github.com/dhall-lang/dhall-lang/blob/master/docs/howtos/Text-Editor-Configuration.md

**Comment by byorgey** [comment]
Relevant comment for emacs setup: https://github.com/byorgey/swarm/pull/158#issue-748350758

**Comment by xsebek** [comment]
I went ahead and hacked together a [highlighter for VSCode](https://marketplace.visualstudio.com/items?itemName=xsebek.swarm-language):

![VSCode with debug](https://user-images.githubusercontent.com/44544735/136986777-a3556563-a0fc-4ded-bc07-2aaf549d75d0.png)

(I guess I could easily change the regexes to create a vim highlighter too)

I tried if the example LSP client from Microsoft docs could be adapted to work with `swarm lsp` (see [this branch](https://github.com/xsebek/swarm-vscode/tree/wip-lsp)), but I really have no idea what interface we are currently using or how to debug that.

Could you please help @TristanCacqueray? :pleading_face:

**Comment by byorgey** [comment]
The error is being shown in the right place. The problem is that it is parsing as a bunch of definitions being applied to a variable `a`, and so they are not at the top level (they are inside an application).  It is just a terrible error message but there's nothing wrong with the source locations or lsp integration.

**Comment by TristanCacqueray** [comment]
@byorgey http://ergoemacs.org/emacs/elisp_syntax_coloring.html seems to be a good documentation for updating emacs swarm-mode.

**Comment by byorgey** [comment]
Turns out configuring emacs syntax highlighting is horrid (who would have guessed?).  But I've made a bit of progress:

![emacs](https://user-images.githubusercontent.com/533859/137003107-69149e2d-f349-4eea-83ba-d380c03db2c6.png)
