### ISSUE TITLE
Store REPL history file in $XDG_DATA_HOME

### ISSUE THREAD

**Issue by RustemB** [byorgey/swarm#136]
why not to save history file somewhere in `$HOME`?
not in `pwd`

**Comment by byorgey** [comment]
Good idea.  We should use https://hackage.haskell.org/package/xdg%2Dbasedir .

**Comment by TristanCacqueray** [comment]
Why not using the facility from `directory`, e.g. https://hackage.haskell.org/package/directory-1.3.7.0/docs/System-Directory.html#v:getXdgDirectory ?

**Comment by byorgey** [comment]
Oh, even better, I didn't know `directory` supported that.
