### ISSUE TITLE
Add a test testing that the examples type-check

### ISSUE THREAD

**Issue by polux** [byorgey/swarm#180]
**Is your feature request related to a problem? Please describe.**
In #176 we could have missed that example/cat.sw had to be updated after a change to the language.

**Describe the solution you'd like**
This should have been caught by a test run by the CI.

**Comment by polux** [comment]
One annoying limitation of cabal is that it doesn't let you declare data-files scoped to only the test suite: https://stackoverflow.com/a/33955353/357732. That means either the tests need to know where to read the example files from (via a flag or by convention), or we bundle the examples in the binary.

**Comment by TristanCacqueray** [comment]
What about using `extra-source-files` ?

**Comment by polux** [comment]
Yes, I think we'll have to use that but my understanding is that this requires the test to be run from the right directory relative to the example files.

**Comment by TristanCacqueray** [comment]
If I understand correctly, the tests are ran from the root directory, e.g. where the `.cabal` file is. Thus it should be safe to get them from `listDirectory "./example"`

**Comment by polux** [comment]
Sounds good. What I meant is that one could choose to run them from somewhere else. But that's unlikely.

**Comment by byorgey** [comment]
Someone really just needs to go through and curate the examples - delete stupid ones, add more, etc. The things that are in there right now are just random things left over from when I was testing out very early versions of the game.
