### ISSUE TITLE
`wait` command and waiting robot queue

### ISSUE THREAD

**Issue by byorgey** [byorgey/swarm#20]
Right now, the only way for a robot to wait for a certain amount of time is to execute a program like `repeat 500 wait`, but this means the robot is doing a bunch of computation steps every tick (evaluating the recursive `repeat` command, subtracting one from a number, checking whether it is zero...).  Instead, there should be a way for a robot to register its intent to sleep for a certain amount of time, and have the game engine wake it up later.  This will save a lot of work --- for example, I have noticed that the game slows down noticeably when harvesting a large forest, generating a large number of system seed robots which are all busily waiting for a long time to grow.

The idea is as follows.  Note that #19 needs to be implemented first.

* Change the `wait` command to take an `int` argument, denoting the duration of waiting.
* Right now the `wait` command requires no capabilities, but perhaps with this change it should.  I propose adding a `time` capability, which can be provided by a new `clock` entity (recipe: some gears + some springs (in turn made from copper wire)?).
    * While we're at it, perhaps we can also add `getTime : cmd int`, also requiring the `time` capability.
* Add a counter to the `GameState` which tracks the number of ticks since the game started.
* Add a priority queue of waiting robots to the `GameState`, keyed by the tick at which the robot should wake up.
* When a robot executes a `wait` command, remove it from the `activeRobots` queue and place it in the priority queue (after calculating the time at which it should be woken).
* Each tick, before iterating through the active robots, check the priority queue and move any robots which should be woken on this time step into the active robot queue.

**Comment by polux** [comment]
Did you have some representation in mind for the active and waiting robots queues?

We can't really split `_robotMap` into two queues because looking up robots by name would then be inefficient. So It seems to me the priority queue has no choice but to point to robot names: `_waitingRobots :: PriorityQueue Time Name`.

As far as I can tell we don't really need a set (or queue) of active robots: we should be able to tell that a robot is waiting based on the state of its CEK machine. So we can filter out waiting robots when looping over `_robotMap` in the `gameTick` function. Still, it may be more efficient to cache the set of waiting robots in `GameState` if most robots are going to be sleeping most of the time.

**Comment by byorgey** [comment]
> So It seems to me the priority queue has no choice but to point to robot names

Agreed.

> So we can filter out waiting robots when looping over `_robotMap` in the `gameTick` function

Good point, I don't really know how much of a difference it would make.  We really need to set up some benchmarks so we can empirically test this sort of thing.

**Comment by byorgey** [comment]
Oh, well, one problem is that if we add a waiting robots queue, now we can no longer tell whether a robot is active just by looking at its CEK machine. But I guess we could just make a flag or a special CEK machine state or something like that.

**Comment by polux** [comment]
The way I am seeing it, you would always be able to tell that a robot is waiting or not based on its CEK machine, and both the waiting and active robot queues would be optimizations.

**Comment by byorgey** [comment]
Ah, I think that makes sense.  I don't know exactly what you have in mind for checking if a robot is waiting via its CEK machine.  But perhaps you have in mind something like adding a special CEK machine state
``` haskell
Wait :: Int -> CEK -> CEK
```
which would mean "wake up at this time and then continue running from this state"?  In conjunction with adding an `int` argument to the `wait` command, this would already be way more efficient than the status quo.

**Comment by polux** [comment]
> But perhaps you have in mind something like adding a special CEK machine state

Something like that. Or if you would prefer not to "pollute" the machine, we could change the robot's state instead.

>  In conjunction with adding an int argument to the wait command, this would already be way more efficient than the status quo.

Exactly, I think we could try that without any queue at first, and it'd probably already be faster than executing the code of `repeat`.

**Comment by byorgey** [comment]
> Or if you would prefer not to "pollute" the machine, we could change the robot's state instead.

I know what you mean about not wanting to "pollute" the machine with extra states, but it seems like this really does belong in the CEK machine state. It explains what the robot is doing and what it will do next.

> Exactly, I think we could try that without any queue at first, and it'd probably already be faster than executing the code of `repeat`.

Sure, let's try it!
