### ISSUE TITLE
`salvage` command

### ISSUE THREAD

**Issue by byorgey** [byorgey/swarm#21]
There ought to be a way to retrieve all the inventory and devices from a "dead" robot.  I'm imagining something like `salvage : string -> cmd ()`, where `salvage x` will try to salvage a robot named `x`.  If successful, all of `x`'s inventory and installed devices go into the inventory of the robot that executed `salvage`, and `x` itself disappears.

Some issues to work out:

* What is the range of the `salvage` command?  I'm thinking probably you have to be in the very same cell.
* What if you don't know the name of the robot you want to salvage? There has to be some other way to discover the name(s) of nearby robot(s).  That should be orthogonal to `salvage`, but it's still worth thinking about them together.
* We'll need to add a new `salvage` capability.  What device should confer this capability, and what should its recipe be?  How difficult should it be to construct?

**Comment by Anrock** [comment]
> There has to be some other way to discover the name(s) of nearby robot(s)
Some ideas ("scan" and "look") in https://github.com/byorgey/swarm/issues/49

**Comment by byorgey** [comment]
I've been working on adding this, and I accidentally `salvage`d the base, and now I can't do anything. :rofl: 

![salvage-base](https://user-images.githubusercontent.com/533859/136491909-81e7d2a1-5c16-4f00-9130-26030b2ea5bd.png)
