### ISSUE TITLE
Better handling of water

### ISSUE THREAD

**Issue by byorgey** [byorgey/swarm#24]
Right now, water is a terrain type, with an entity for waves so that water can have a checkerboard of waves.  But robots can walk right across it, and there's no way for robots to obtain any water.  This should be handled in a different way.

Here are my current ideas:

* Make water an entity with properties [portable, drown, growable].  `drown` is a new property that means any robot walking on it will drown (i.e. instantly disappear).
* Get rid of the water terrain type.
* Change the world generation function to generate water entities on top of e.g. dirt terrain, instead of water terrain.
* Make a `boat` device (constructible out of boards?) that conveys a `float` capability.  Robots with the `float` capability do not die when walking on top of an entity with the `drown` property.  The logic about `drown` and `float` will need to be added to the interpretation of the `Move` command in `Swarm.Game.Step`.
* This should be done in conjunction with #23 , to give water a growth time of 0 (i.e. as soon as a robot picks it up, there is more water generated there).
* Consider whether a robot needs to have some special device to collect water, or if a grabber device should be sufficient.
* Make water able to have two "orientations" in its display map so we can have some water entities with waves and some without.
* Modify hashing for entities so the current orientation is NOT taken into account when hashing.  What direction an entity is facing should not affect its identity, and in this case it means we can have water entities which are identical when picked up but have two different appearances in the world.

**Comment by GnarLito** [comment]
Another issue this create is how to determine when the `boat` device should be added to a robot, Since the `boat` device doesn't have any programmable logic connected to it.

A way to get around this is by adding a another parameter to the build command that accepts the extra devices to be installed or by making an useless function that requires the `boat` device to make it install.

But a better way to do this is by making the `boat` a global upgrade that once created will be added to all new robots. This would also make it easier to add other upgrades (carrying capacity for example).

For now it would be okay to let the `grab` command collect water, But it depends where in the tech tree water would be needed.

**Comment by byorgey** [comment]
> Another issue this create is how to determine when the `boat` device should be added to a robot, Since the `boat` device doesn't have any programmable logic connected to it.

Good point.  I don't really want to complicate the `build` command with extra parameters.  I'm also not sure I really like the idea of global upgrades.  However, I think there is a simpler solution: once we add an `install` command (see #92) you can just `install` a boat on a robot once it has been built.  You might complain that it is annoying to have to manually do that extra step, but, well, that is what programming is for, e.g.:
```
buildWithBoat : string -> cmd () -> cmd () = \name. \prog. build name {wait; wait; prog}; install name "boat"
```

> For now it would be okay to let the `grab` command collect water, But it depends where in the tech tree water would be needed.

Yes, good point, I am not sure yet.  We can easily change it later.

**Comment by GnarLito** [comment]
I agree the `install` command would fix this.

As for gathering water, we could say that the `grab` alone gets 1 water a time and that u could "upgrade" the gathering by install a `bukkit`device to get like 10 water a time and after "upgrade" it by installing a `pump` device for like 100 water a time.
But this is really needed if water becomes a major part in the game.

**Comment by byorgey** [comment]
Yeah, OK, I like that idea.

**Comment by byorgey** [comment]
I have this mostly implemented now.  One question that occurs to me, though: how should `move`ing on water be handled?  It depends how realistic we want to be.  Intuitively, if `treads` are what allow a robot to `move`, it does not really make sense that a robot in a boat, floating on water, could use its treads to move...
