### ISSUE TITLE
Show command and string concatenation

### ISSUE THREAD

**Issue by xsebek** [byorgey/swarm#248]
I would like `log` to have signature `a -> cmd ()` instead of current `string -> cmd ()`.
The use case I have in mind is to log an `int`, for example in this loop:
```haskell
def iterate = \c.\b. bn <- c b; iterate c b end
build "loop" {iterate {\i. move; turn back; log i; return (i+1)} 0}
```
But we can print any type, so I see no reason why we should not allow that. :thinking: 

The alternative would be to provide a `show` function or some other functions operating on string.

**Comment by byorgey** [comment]
Yeah, I was thinking about this the other day.  I think instead of generalizing `log` we should indeed provide a `show` function and an `<>` operator for string concatenation (or some other names).  It seems like that would be more generally useful.

**Comment by xsebek** [comment]
Sure, we could have logger provide those for now. :slightly_smiling_face: 

This may be orthogonal, but could we also add `kind` or `showType`? I often type `\c. someExpression` just to print the type.

**Comment by byorgey** [comment]
Bikeshedding time: what should we call the built-in `a -> string` function?  We could be Haskelly and call it `show` of course.  But maybe something like `str` or `fmt` (or something else) would be a better generic name?
