### ISSUE TITLE
File precheck

### ISSUE THREAD

**Issue by Zuzuk-null** [byorgey/swarm#249]
The game does not check the file before using it. Thus, you can use binary (such as bash) files, or even links to special system files (for example, /dev/zero). In the best case, the game will simply crashes, but it can also freeze the computer

**Comment by byorgey** [comment]
Thanks for the report!  Can you give an example of an input that will crash the game or freeze the computer?  What kind of check do you think we should do?

**Comment by byorgey** [comment]
Closing since I'm not exactly sure what kind of scenario is in mind here.  Feel free to reopen with some more specific examples.
