### ISSUE TITLE
Report error in def body only

### ISSUE THREAD

**Issue by xsebek** [byorgey/swarm#268]
Currently typing errors are shown as a problem of the expression - which usually means the whole file.

Good error:
![](https://user-images.githubusercontent.com/44544735/139477184-ae9a8e56-2bc5-40b0-9f8b-9a65845f3c61.png)

Bad error:
![](https://user-images.githubusercontent.com/44544735/139477214-10ed5527-10f4-4df5-8c03-c8f63d4d8106.png)

In principle we should be able to report the error in the body of definition where the error occurred. The previous `def`s, `let`s and commands must have been fine as we checked them. They could of course lead to the failure in some later part, but only indirectly.

At minimum we should be able to split at `def`s as those must be at global scope and each individually typecheck.

**Comment by byorgey** [comment]
Yes, we could definitely do a better job reporting the locations of type errors than we currently do.  The changes required range from pretty easy to very complex depending how sophisticated you want to be about it.  Some related issues include #99, #109, and #124.

**Comment by xsebek** [comment]
For this issue I would like to be minimal, if the scope of the error is at most the offending def body, then that is good enough. :slightly_smiling_face: 

My use case is porting scripts between swarm versions (e.g. pre-delay) which could be easily done top-down if the error was shown at the first offending `def` and not before. A small improvement could make the LSP much more useful tool for this task.

Hopefully this is just some missing or unfortunately placed `addLocToTypeErr` in `infer` that overwrites the location with too general context, but I do not understand that machinery very well and it might be a more complicated problem.
