### ISSUE TITLE
Get impossible operations to return a random result

### ISSUE THREAD

**Issue by byorgey** [byorgey/swarm#27]
A few pure operations (comparison on certain types, e.g. function types; division by zero; exponentiation by a negative number) typecheck but have undefined semantics.  Making them not typecheck would require adding too much complexity to the type system; and we don't want them to throw exceptions since right now only commands can throw exceptions (giving pure expressions the ability to throw exceptions would make a lot of things more complicated too).

Instead, right now, these operations return a certain magic constant (`False` in the case of comparison; `42` in the case of division and exponentiation).  However, it would be more fun if they returned a *random* result of the appropriate type.  This would entail figuring out how to thread the capability to generate randomness through the interpreter (right now it is done using `IO` for the `random` command but I'd like to get rid of that if we can).

**Comment by xsebek** [comment]
Since #170 the GameState holds a random generator, so this might be slightly easier. 🙂

**Comment by polux** [comment]
This means you get the capability to generate random numbers as soon as you get division. Is that ok?
