### ISSUE TITLE
Comments alone are invalid

### ISSUE THREAD

**Issue by xsebek** [byorgey/swarm#275]
#### Describe the bug

Inputs like
```c
// commented out expression because I forgot to "run somefile" first
```
are invalid, while
```c
()// commented out expression because I forgot to "run somefile" first
```
is fine. Ideally such hacks would not be required to use comments.

#### Expected behavior

Ideally even empty line would be valid.

#### Additional context

This is also annoying in editors with LSP when starting a file with a comment which is invalid until some code is added too.

**Comment by byorgey** [comment]
Good catch.  I think this *might* be fixed by changing `sepEndBy1` to `sepEndBy` in `parseTerm`:

https://github.com/byorgey/swarm/blob/8deb10f3b7957c5d09155747306fab27a8e0ecb7/src/Swarm/Language/Parse.hs#L273

Off the top of my head I'm not sure whether that would break anything.

**Comment by byorgey** [comment]
Ah, no, of course that is not going to work.  Perhaps we should (1) change the type of `readTerm` to `Text -> Either Text (Maybe Syntax)` (and similarly `readTerm'`), and (2) make `readTerm` able to parse either `parseTerm` or just whitespace (including comments).
