### ISSUE TITLE
Add toggle key for hiding 0 in inventory

### ISSUE THREAD

**Issue by xsebek** [byorgey/swarm#282]
From #49 - let's add a toggle key that would hide/show entities with count 0.
This could shorten the length of the inventory in some situations.

As an alternative we could:
- add a separate list of "Known entities" below installed devices
- abandon this idea and revive #126 instead

**Comment by noahyor** [comment]
I will see if I can work on this, though it might take a while taking into account my low to moderate haskell skills and my limited time allotment.

**Comment by noahyor** [comment]
Could you help me change populateInventoryList in src/Swarm/TUI/Model.hs please?

**Comment by noahyor** [comment]
On the seedcrash branch, of course.

**Comment by byorgey** [comment]
The primary thing you will have to do is change the logic of the `shouldDisplay` function: https://github.com/byorgey/swarm/blob/ceaa949455749077107648f73d79e32771685619/src/Swarm/TUI/Model.hs#L502

You can write something like `showZeros <- use uiShowZeros` right after the line `mList <- preuse ...` to access the `uiShowZeros` field (or whatever you called it) in the `UIState` and assign it to the variable `showZeros`.  Then you can use that variable in the logic for `shouldDisplay`.

**Comment by noahyor** [comment]
OK, but what logic should I use, `(not showZero) && (n > 0) || not ...` or wrap the whole thing in `showZero && (...)` ?

**Comment by byorgey** [comment]
I think you just need to add `showZero &&` to the `not ...` part.  If `n > 0` then we definitely want to show the entity no matter what.  Otherwise, we want to show it only if BOTH (1) `showZero` is true, and (2) it's not an installed device.

**Comment by noahyor** [comment]
I'm done! (I actually had a lot more time than expected) Should I just commit & push or should I open a new pull request?
