### ISSUE TITLE
`reprogram` does not work

### ISSUE THREAD

**Issue by xsebek** [byorgey/swarm#287]
The `reprogram` command does not seem to work for me:
```
build "a" {move}
reprogram "a" {move; move}
```
I would expect the result
```
Ω  >
```
But instead the reprogram never finishes executing:
```
Ω>
```
When reprogramming base, it goes into `. . .`, but does not move.

EDIT: Further retries give:
```
┌─────────────── · · · ────────────────┐
│ reprogram: You cannot reprogram a    │
│   robot that has not completed its   │
│   current command                    │
└──────────────────────────────────────┘
```

**Comment by byorgey** [comment]
@xsebek thanks for the report!  Not sure how we missed this.  I think it should be fixed now but please check.  Reprogramming the base works fine for me, for example

```
build "y" {wait 5; reprogram "base" {build "z" {move; move; move}}}
```

works as expected.

**Comment by xsebek** [comment]
Thanks for the quick fix @byorgey, I was looking around that code and completely missed the missing activation :+1: 

Now reprogramming both robots and base works without issue :slightly_smiling_face:
