### ISSUE TITLE
Line-wrap recipes

### ISSUE THREAD

**Issue by amalloy** [byorgey/swarm#48]
Tried the game out today, and I couldn't do anything with copper until I read the source, because recipes do not fit in the recipe pane, even if I make my terminal much wider than I usually would. Recipes like the one for copper wire are too long to fit into the pane, and are just clipped at the end, so I knew I could craft "co[something]", but had no way to find out more.

**Comment by byorgey** [comment]
Recipes are line-wrapped now, but I'm leaving this ticket open because I want the wrapped lines to be indented.  See the comment on https://github.com/byorgey/swarm/commit/cdaef2decc47d7e8167cc5ca87defe41a8be539c .

**Comment by amalloy** [comment]
There's a similar problem with messages printed by surprised robots, e.g. when one tries to move through a boulder. I tried switching `drawMessages` to use `txtWrap`. This sorta works, but then there's a new problem because you assume you have enough space to render one message per available line.

**Comment by byorgey** [comment]
Right, that issue is already recorded as #36 .  In general, I think the info box in the bottom left needs to be changed to use a scrollable viewport, with some way to let the user scroll it.  We are also pretty quickly going to run into issues where item descriptions are too long to fit in the box.
