### ISSUE TITLE
swarm runs at 100% CPU

### ISSUE THREAD

**Issue by ffaf1** [byorgey/swarm#55]
**Describe the bug**
`swarm` runs at 100% CPU

**To Reproduce**
Run `swarm`. In another terminal, run `top`:

````
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
388509 f         20   0 1024.3g  32808  14516 R 100.0   1.1   0:06.59 swarm
````

(alternative: listen to your PC’s fan)

**Expected behavior**
Use less CPU cycles.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by byorgey** [comment]
Thanks for the report!  This is already being discussed over at #47 and there should be a fix soon.
