### ISSUE TITLE
Left pane dissapear on map exploration. Is this the desired behaviour?

### ISSUE THREAD

**Issue by lsmor** [byorgey/swarm#70]
**Description**
The top-left pane becomes blank when you press the arrow keys (or hjkl) to explore the map. It becomes visible again when pressing `c` to recenter. It doesn't affect the game too much but, Is this the desired behaviour?

**To Reproduce**
- Open the game.
- Press `Tab` to highlight the Map pane.
- Press the arrow keys. The top left pane should have disappeared
- Press `c`. The top left pane should have re-appeared

**Expected behavior**
Top left pane should be visible always

**Screenshots**

Everything looks alright on game start
![image](https://user-images.githubusercontent.com/58398442/134777097-cad480ae-1df6-4e50-9291-8a5ddb4fcef4.png)

When pressing arrow keys, the top left pane goes away

![image](https://user-images.githubusercontent.com/58398442/134777136-e1980f80-53d5-47c0-90e7-38fa1a418757.png)

When pressing `c` It shows up agains

![image](https://user-images.githubusercontent.com/58398442/134777169-a433bb8a-ac8c-4ab7-b8c2-0c3df63d618f.png)

**Comment by byorgey** [comment]
Hi, thanks for the report!  This is not technically a bug --- as in, I originally made it this way on purpose --- but I agree it is not good, and the robot inventory should stay there even if you scroll around the map.  In fact I already made #61 to track this.   I will close this as duplicate but really appreciate you taking the time to file an issue --- it just confirms for me that this was not the right design and we should fix it!
