### ISSUE TITLE
libtinfo.so: cannot open shared object file: No such file or directory - Linker error

### ISSUE THREAD

**Issue by twitu** [byorgey/swarm#73]
**Describe the bug**
Building the project for the first time produces this error a linker error.

```
<no location info>: warning: [-Wmissed-extra-shared-lib]
    libtinfo.so: cannot open shared object file: No such file or directory
    It's OK if you don't want to use symbols from it directly.
    (the package DLL is loaded by the system linker
     which manages dependencies by itself).

<skip-lines>
```

**To Reproduce**
This happens if certain static libraries are not installed on your system

**Expected behavior**
The build should have succeeded

**Additional context**
I am running this one wsl 2 Ubuntu. But this can occur on other systems that do not have the required static libraries.

**Comment by twitu** [comment]
I solved this by installing the required libraries using `sudo apt-get libncurses5 libncurses5-dev -y`. This installs the required static libraries.

**Comment by twitu** [comment]
It might be a good idea to list the required static libraries required to build and run the game or create a docker image with everything required to build and run or develop on the game.

**Comment by byorgey** [comment]
Thanks for the report!  Closing this in favor of #69 .
