### ISSUE TITLE
Clear the error widget on successfull REPL entry

### ISSUE THREAD

**Issue by TristanCacqueray** [byorgey/swarm#76]
**Is your feature request related to a problem? Please describe.**
When an error is displayed, it seems like the only way to remove from the screen it is by pressing `Esc`.

**Describe the solution you'd like**
When a new REPL entry is validated, any previous error should be removed from the screen.

**Comment by byorgey** [comment]
Sounds like a nice idea.  Can you clarify what you mean by "when a new REPL entry is validated"? Do you mean when the user hits "Enter", or do you mean as soon as the REPL contains some text which validates?

**Comment by TristanCacqueray** [comment]
I meant when the user hits "Enter" and the entry is validated (e.g. when added to the repl history), that should be a good place to remove any uiError.

**Comment by byorgey** [comment]
> I meant when the user hits "Enter" and the entry is validated (e.g. when added to the repl history), that should be a good place to remove any uiError.

I see, makes sense to me.

**Comment by TristanCacqueray** [comment]
Thanks @Alexander-Block !
