### ISSUE TITLE
Add a command line argument to validate and/or load an initial program file into the base

### ISSUE THREAD

**Issue by TristanCacqueray** [byorgey/swarm#82]
**Is your feature request related to a problem? Please describe.**
When working on robot code written in a file, it is not super convenient to use the in-game repl.

**Describe the solution you'd like**
The CLI could features an argument parser to handle `--load file` argument to perform the initial `run` command.

**Describe alternatives you've considered**
A `--check` argument could also be used to just validate the code without running the game.

**Comment by byorgey** [comment]
Can you describe in more detail how this would be more convenient than the status quo? It sounds like it would only work at startup, so it wouldn't help you if you wanted to reload the definitions in the middle of a game.

I am not at all opposed to this feature, but it doesn't seem to me like it would add all that much convenience.  Personally I would rather put some effort into #7 which seems like it would be a much bigger improvement.

**Comment by TristanCacqueray** [comment]
As I was working around #79 , I had to keep the game open and replay the `run("my.swarm")` until the error got fixed. Moreover it might be interesting to play the game without interaction, e.g. write everything in advance and run `swarm --load ./my.swarm`.

Though I agree #7 is more important.

**Comment by juhp** [comment]
I still feel a `load` command would be a useful feature: it is easier to write `swarm load path/to/bots.sw` using shell completion, than guessing the path in `run("path/to/bots.sw")` say.

**Comment by byorgey** [comment]
Sure, we can reopen this. Implementing a `--run` option should not be hard. (I think it ought to be named the same as the corresponding command.)

**Comment by xsebek** [comment]
I was planning to take a look at #7, but if anyone else has more time, feel free to take a shot at this :wink:
