### ISSUE TITLE
`has` command

### ISSUE THREAD

**Issue by byorgey** [byorgey/swarm#88]
We should add a command `has : string -> cmd bool` which determines whether the robot has any of the named entity in its inventory.  This would be useful for implementing things like `giveAll`:
```
def whileC : forall a. cmd bool -> cmd a -> cmd () = \test. \body. 
  b <- test; 
  if b (body ; whileC test body) {} 
end;
def giveAll : string -> string -> cmd () = \other. \thing.
  whileC (has thing) { 
    give other thing 
  } 
end
```

**Comment by TristanCacqueray** [comment]
The code sample is a bit hard to read, should it uses a carriage return before the body? e.g.

```
def whileC : forall a. cmd bool -> cmd a -> cmd () = \test. \body.
  b <- test; if b (body ; whileC test body) {}
end;
```

**Comment by byorgey** [comment]
Yeah, good point, I reformatted it to make it easier to read.

It also occurs to me that it would probably be better to give it the type `string -> cmd int`, where it returns the number of that thing you have, rather than just a boolean.  Of course given this you could recover the boolean version by comparing the result to zero.  The general principle here is that we should return as much information as possible.
