### ISSUE TITLE
Giving an object to oneself destroys the object

### ISSUE THREAD

**Issue by gilgamec** [byorgey/swarm#91]
**Describe the bug**

Using the command `give` to give an object to oneself destroys the object. For instance, if the base is issued the command `give "base" "tree"`, one tree is deleted from the base's stockpile. This seems to work for robot entities too.

**To Reproduce**

Get a tree at base. Issue the command `give "base" "tree"`. Number of trees in inventory decreases by one.

Seems to work with robots too. The robot
```
build "fetch" { turn west; m8; grab; turn east; m8; give "fetch" "tree"; give "base" "tree"; }
```
does not give a tree to the base.

**Expected behavior**

Giving an object to oneself should be a no-op.

**Comment by byorgey** [comment]
Good catch, thanks!  Should be fixed now!
